name: example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
# markdown_tooltip: ^0.0.6
  markdown_tooltip:
    path: ..

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
